/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as AuthenticatedObrasRouteImport } from './routes/_authenticated/obras'
import { Route as AuthenticatedMovimentacoesRouteImport } from './routes/_authenticated/movimentacoes'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObrasRoute = AuthenticatedObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovimentacoesRoute =
  AuthenticatedMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/obras': typeof AuthenticatedObrasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/obras': typeof AuthenticatedObrasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/_authenticated/obras': typeof AuthenticatedObrasRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/estoque'
    | '/movimentacoes'
    | '/obras'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/estoque' | '/movimentacoes' | '/obras' | '/usuarios' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/estoque'
    | '/_authenticated/movimentacoes'
    | '/_authenticated/obras'
    | '/_authenticated/usuarios'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras': {
      id: '/_authenticated/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof AuthenticatedObrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimentacoes': {
      id: '/_authenticated/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedMovimentacoesRoute: typeof AuthenticatedMovimentacoesRoute
  AuthenticatedObrasRoute: typeof AuthenticatedObrasRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedMovimentacoesRoute: AuthenticatedMovimentacoesRoute,
  AuthenticatedObrasRoute: AuthenticatedObrasRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
